
/**
 * Mansion Protocol - Asset Generation Script
 * 
 * 这个脚本用于将 raw_data 目录下的分散 JSON 文件合并为前端可用的 TypeScript 数据模块。
 * 
 * 使用方法:
 * node scripts/generate_assets.js
 */

const fs = require('fs');
const path = require('path');

// --- 配置 ---

const RAW_DIR = path.join(__dirname, '../raw_data');
const OUT_DIR = path.join(__dirname, '../data/source');

// 定义每个数据类别的处理规则
const CATEGORIES = {
    'characters': { 
        outputFile: 'characters.ts', 
        varName: 'CHARACTERS_DATA', 
        type: 'ARRAY' // 合并所有数组文件
    },
    'tiles': { 
        outputFile: 'tiles.ts', 
        varName: 'TILES_DATA', 
        type: 'ARRAY' 
    },
    'items': { 
        outputFile: 'items.ts', 
        varName: 'ITEMS_DATA', 
        type: 'OBJECT' // 合并所有对象文件 (key-value)
    },
    'events': { 
        outputFile: 'events.ts', 
        varName: 'EVENTS_DATA', 
        type: 'OBJECT' 
    },
    'skills': { 
        outputFile: 'skills.ts', 
        varName: 'SKILLS_DATA', 
        type: 'OBJECT' 
    },
    'scenarios': { 
        outputFile: 'scenarios.ts', 
        varName: 'SCENARIOS_DATA', 
        type: 'OBJECT' 
    }
};

// --- 工具函数 ---

function ensureDirectoryExistence(filePath) {
    const dirname = path.dirname(filePath);
    if (fs.existsSync(dirname)) {
        return true;
    }
    ensureDirectoryExistence(dirname);
    fs.mkdirSync(dirname);
}

function readJsonFiles(dirPath, mergeType) {
    if (!fs.existsSync(dirPath)) {
        console.warn(`[WARN] Directory not found: ${dirPath}`);
        return mergeType === 'ARRAY' ? [] : {};
    }

    const files = fs.readdirSync(dirPath).filter(file => file.endsWith('.json'));
    let result = mergeType === 'ARRAY' ? [] : {};

    console.log(`[INFO] Reading ${files.length} files from ${path.basename(dirPath)}...`);

    files.forEach(file => {
        const filePath = path.join(dirPath, file);
        try {
            const content = fs.readFileSync(filePath, 'utf8');
            const json = JSON.parse(content);

            if (mergeType === 'ARRAY') {
                if (Array.isArray(json)) {
                    result = [...result, ...json];
                } else {
                    console.warn(`[WARN] File ${file} expected Array but got Object. Skipped.`);
                }
            } else {
                if (typeof json === 'object' && !Array.isArray(json)) {
                    result = { ...result, ...json };
                } else {
                    console.warn(`[WARN] File ${file} expected Object but got Array. Skipped.`);
                }
            }
        } catch (err) {
            console.error(`[ERR] Failed to parse ${file}: ${err.message}`);
        }
    });

    return result;
}

function generateTsContent(varName, data) {
    const jsonString = JSON.stringify(data, null, 2);
    return `
// This file is auto-generated by scripts/generate_assets.js
// Do not edit this file directly. Edit the JSON files in raw_data/ instead.

export const ${varName} = ${jsonString};
`;
}

// --- 主流程 ---

console.log('--- Starting Asset Generation ---');

Object.keys(CATEGORIES).forEach(key => {
    const config = CATEGORIES[key];
    const sourceDir = path.join(RAW_DIR, key);
    const targetFile = path.join(OUT_DIR, config.outputFile);

    // 1. 读取并合并数据
    const mergedData = readJsonFiles(sourceDir, config.type);

    // 2. 生成 TypeScript 内容
    const fileContent = generateTsContent(config.varName, mergedData);

    // 3. 写入文件
    try {
        ensureDirectoryExistence(targetFile);
        fs.writeFileSync(targetFile, fileContent);
        console.log(`[SUCCESS] Generated ${config.outputFile}`);
    } catch (err) {
        console.error(`[ERR] Failed to write ${config.outputFile}: ${err.message}`);
    }
});

console.log('--- Generation Complete ---');
